language: node_js
node_js:
  - 4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjpeg62
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
